<?php

/**
 * This is the model base class for the table "curso_has_mat_didactico".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CursoHasMatDidactico".
 *
 * Columns in table "curso_has_mat_didactico" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $MAT_DIDACTICO_ID
 * @property integer $CURSO_EDICION_ID
 *
 */
abstract class BaseCursoHasMatDidactico extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'curso_has_mat_didactico';
    }

    public static function representingColumn() {
        return array(
            'MAT_DIDACTICO_ID',
            'CURSO_EDICION_ID',
        );
    }

    public function rules() {
        return array(
            array('MAT_DIDACTICO_ID, CURSO_EDICION_ID', 'required'),
            array('MAT_DIDACTICO_ID, CURSO_EDICION_ID', 'numerical', 'integerOnly'=>true),
            array('MAT_DIDACTICO_ID, CURSO_EDICION_ID', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'MAT_DIDACTICO_ID' => Yii::t('app', 'Mat Didactico'),
                'CURSO_EDICION_ID' => Yii::t('app', 'Curso Edicion'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('MAT_DIDACTICO_ID', $this->MAT_DIDACTICO_ID);
        $criteria->compare('CURSO_EDICION_ID', $this->CURSO_EDICION_ID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}