<?php

/**
 * This is the model base class for the table "evaluacion_estudiante".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EvaluacionEstudiante".
 *
 * Columns in table "evaluacion_estudiante" available as properties of the model,
 * followed by relations of table "evaluacion_estudiante" available as properties of the model.
 *
 * @property integer $ID
 * @property integer $NOTA
 * @property integer $PERSONA_ID
 * @property integer $CURSO_EDICION_ID
 *
 * @property Persona $pERSONA
 * @property CursoEdicion $cURSOEDICION
 */
abstract class BaseEvaluacionEstudiante extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'evaluacion_estudiante';
    }

    public static function representingColumn() {
        return 'ID';
    }

    public function rules() {
        return array(
            array('NOTA, PERSONA_ID, CURSO_EDICION_ID', 'required'),
            array('NOTA, PERSONA_ID, CURSO_EDICION_ID', 'numerical', 'integerOnly'=>true),
            array('ID, NOTA, PERSONA_ID, CURSO_EDICION_ID', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'pERSONA' => array(self::BELONGS_TO, 'Persona', 'PERSONA_ID'),
            'cURSOEDICION' => array(self::BELONGS_TO, 'CursoEdicion', 'CURSO_EDICION_ID'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'NOTA' => Yii::t('app', 'Nota'),
                'PERSONA_ID' => Yii::t('app', 'Persona'),
                'CURSO_EDICION_ID' => Yii::t('app', 'Curso Edicion'),
                'pERSONA' => null,
                'cURSOEDICION' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('NOTA', $this->NOTA);
        $criteria->compare('PERSONA_ID', $this->PERSONA_ID);
        $criteria->compare('CURSO_EDICION_ID', $this->CURSO_EDICION_ID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}