<?php

/**
 * This is the model base class for the table "horario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Horario".
 *
 * Columns in table "horario" available as properties of the model,
 * followed by relations of table "horario" available as properties of the model.
 *
 * @property integer $ID
 * @property string $HORA_INICIO
 * @property string $HORA_FIN
 * @property integer $NUM_HORAS
 * @property string $DETALLE
 *
 * @property CursoEdicion[] $cursoEdicions
 */
abstract class BaseHorario extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'horario';
    }

    public static function representingColumn() {
        return 'HORA_INICIO';
    }

    public function rules() {
        return array(
            array('HORA_INICIO, HORA_FIN, NUM_HORAS, DETALLE', 'required'),
            array('NUM_HORAS', 'numerical', 'integerOnly'=>true),
            array('DETALLE', 'length', 'max'=>14),
            array('DETALLE', 'in', 'range' => array('LUNES-VIERNES','SABADO-DOMINGO')), // enum,
            array('ID, HORA_INICIO, HORA_FIN, NUM_HORAS, DETALLE', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cursoEdicions' => array(self::HAS_MANY, 'CursoEdicion', 'HORARIO_ID'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'HORA_INICIO' => Yii::t('app', 'Hora Inicio'),
                'HORA_FIN' => Yii::t('app', 'Hora Fin'),
                'NUM_HORAS' => Yii::t('app', 'Num Horas'),
                'DETALLE' => Yii::t('app', 'Detalle'),
                'cursoEdicions' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('HORA_INICIO', $this->HORA_INICIO, true);
        $criteria->compare('HORA_FIN', $this->HORA_FIN, true);
        $criteria->compare('NUM_HORAS', $this->NUM_HORAS);
        $criteria->compare('DETALLE', $this->DETALLE, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}