<?php

/**
 * This is the model base class for the table "formulario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Formulario".
 *
 * Columns in table "formulario" available as properties of the model,
 * followed by relations of table "formulario" available as properties of the model.
 *
 * @property integer $ID
 * @property integer $CONOCIMIENTOS
 * @property integer $PUNTUALIDAD
 * @property integer $MAT_DIDACTICO
 * @property integer $FORMA_ENSENANZA
 * @property integer $ESTUDIANTE_ID
 * @property integer $INSTRUCTOR_ID
 * @property integer $CURSO_EDICION_ID
 *
 * @property CursoEdicion $cURSOEDICION
 */
abstract class BaseFormulario extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'formulario';
    }

    public static function representingColumn() {
        return 'ID';
    }

    public function rules() {
        return array(
            array('ESTUDIANTE_ID, INSTRUCTOR_ID, CURSO_EDICION_ID', 'required'),
            array('CONOCIMIENTOS, PUNTUALIDAD, MAT_DIDACTICO, FORMA_ENSENANZA, ESTUDIANTE_ID, INSTRUCTOR_ID, CURSO_EDICION_ID', 'numerical', 'integerOnly'=>true),
            array('CONOCIMIENTOS, PUNTUALIDAD, MAT_DIDACTICO, FORMA_ENSENANZA', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, CONOCIMIENTOS, PUNTUALIDAD, MAT_DIDACTICO, FORMA_ENSENANZA, ESTUDIANTE_ID, INSTRUCTOR_ID, CURSO_EDICION_ID', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cURSOEDICION' => array(self::BELONGS_TO, 'CursoEdicion', 'CURSO_EDICION_ID'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'CONOCIMIENTOS' => Yii::t('app', 'Conocimientos'),
                'PUNTUALIDAD' => Yii::t('app', 'Puntualidad'),
                'MAT_DIDACTICO' => Yii::t('app', 'Mat Didactico'),
                'FORMA_ENSENANZA' => Yii::t('app', 'Forma Ensenanza'),
                'ESTUDIANTE_ID' => Yii::t('app', 'Estudiante'),
                'INSTRUCTOR_ID' => Yii::t('app', 'Instructor'),
                'CURSO_EDICION_ID' => Yii::t('app', 'Curso Edicion'),
                'cURSOEDICION' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('CONOCIMIENTOS', $this->CONOCIMIENTOS);
        $criteria->compare('PUNTUALIDAD', $this->PUNTUALIDAD);
        $criteria->compare('MAT_DIDACTICO', $this->MAT_DIDACTICO);
        $criteria->compare('FORMA_ENSENANZA', $this->FORMA_ENSENANZA);
        $criteria->compare('ESTUDIANTE_ID', $this->ESTUDIANTE_ID);
        $criteria->compare('INSTRUCTOR_ID', $this->INSTRUCTOR_ID);
        $criteria->compare('CURSO_EDICION_ID', $this->CURSO_EDICION_ID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}