<?php

/**
 * This is the model base class for the table "edicion_curso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EdicionCurso".
 *
 * Columns in table "edicion_curso" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ID
 * @property integer $ID_CURSO
 * @property string $NOMBRE
 * @property string $CONTENIDO
 * @property string $PRERREQUISITOS
 * @property string $ESPECIALIDAD
 * @property integer $ID_EDICION
 * @property integer $NRO_EDICION
 * @property string $FECHA_INICIO
 * @property string $FECHA_FINALIZACION
 * @property string $AULA
 * @property integer $NRO_ESTUDIANTES
 * @property integer $HORARIO_ID
 *
 */
abstract class BaseEdicionCurso extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'edicion_curso';
    }

    public static function representingColumn() {
        return 'NOMBRE';
    }

    public function rules() {
        return array(
            array('ID_CURSO, ID_EDICION, NRO_EDICION, NRO_ESTUDIANTES, HORARIO_ID', 'numerical', 'integerOnly'=>true),
            array('NOMBRE, ESPECIALIDAD, AULA', 'length', 'max'=>20),
            array('CONTENIDO, PRERREQUISITOS', 'length', 'max'=>100),
            array('FECHA_INICIO, FECHA_FINALIZACION', 'safe'),
            array('ID_CURSO, NOMBRE, CONTENIDO, PRERREQUISITOS, ESPECIALIDAD, ID_EDICION, NRO_EDICION, FECHA_INICIO, FECHA_FINALIZACION, AULA, NRO_ESTUDIANTES, HORARIO_ID', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, ID_CURSO, NOMBRE, CONTENIDO, PRERREQUISITOS, ESPECIALIDAD, ID_EDICION, NRO_EDICION, FECHA_INICIO, FECHA_FINALIZACION, AULA, NRO_ESTUDIANTES, HORARIO_ID', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'ID_CURSO' => Yii::t('app', 'Id Curso'),
                'NOMBRE' => Yii::t('app', 'Nombre'),
                'CONTENIDO' => Yii::t('app', 'Contenido'),
                'PRERREQUISITOS' => Yii::t('app', 'Prerrequisitos'),
                'ESPECIALIDAD' => Yii::t('app', 'Especialidad'),
                'ID_EDICION' => Yii::t('app', 'Id Edicion'),
                'NRO_EDICION' => Yii::t('app', 'Nro Edicion'),
                'FECHA_INICIO' => Yii::t('app', 'Fecha Inicio'),
                'FECHA_FINALIZACION' => Yii::t('app', 'Fecha Finalizacion'),
                'AULA' => Yii::t('app', 'Aula'),
                'NRO_ESTUDIANTES' => Yii::t('app', 'Nro Estudiantes'),
                'HORARIO_ID' => Yii::t('app', 'Horario'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('ID_CURSO', $this->ID_CURSO);
        $criteria->compare('NOMBRE', $this->NOMBRE, true);
        $criteria->compare('CONTENIDO', $this->CONTENIDO, true);
        $criteria->compare('PRERREQUISITOS', $this->PRERREQUISITOS, true);
        $criteria->compare('ESPECIALIDAD', $this->ESPECIALIDAD, true);
        $criteria->compare('ID_EDICION', $this->ID_EDICION);
        $criteria->compare('NRO_EDICION', $this->NRO_EDICION);
        $criteria->compare('FECHA_INICIO', $this->FECHA_INICIO, true);
        $criteria->compare('FECHA_FINALIZACION', $this->FECHA_FINALIZACION, true);
        $criteria->compare('AULA', $this->AULA, true);
        $criteria->compare('NRO_ESTUDIANTES', $this->NRO_ESTUDIANTES);
        $criteria->compare('HORARIO_ID', $this->HORARIO_ID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}