<?php

/**
 * This is the model base class for the table "curso_edicion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CursoEdicion".
 *
 * Columns in table "curso_edicion" available as properties of the model,
 * followed by relations of table "curso_edicion" available as properties of the model.
 *
 * @property integer $ID
 * @property string $FECHA_INICIO
 * @property string $FECHA_FINALIZACION
 * @property string $AULA
 * @property integer $NRO_ESTUDIANTES
 * @property integer $CURSO_ID
 * @property integer $HORARIO_ID
 *
 * @property CentroRecaudacionDepositos[] $centroRecaudacionDepositoses
 * @property Certificado[] $certificados
 * @property Curso $cURSO
 * @property Horario $hORARIO
 * @property Persona[] $personas
 * @property EvaluacionEstudiante[] $evaluacionEstudiantes
 * @property FaltasEstudiante[] $faltasEstudiantes
 * @property Formulario[] $formularios
 */
abstract class BaseCursoEdicion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'curso_edicion';
    }

    public static function representingColumn() {
        return 'FECHA_INICIO';
    }

    public function rules() {
        return array(
            array('FECHA_INICIO, FECHA_FINALIZACION, AULA, NRO_ESTUDIANTES, CURSO_ID, HORARIO_ID', 'required'),
            array('NRO_ESTUDIANTES, CURSO_ID, HORARIO_ID', 'numerical', 'integerOnly'=>true),
            array('AULA', 'length', 'max'=>20),
            array('ID, FECHA_INICIO, FECHA_FINALIZACION, AULA, NRO_ESTUDIANTES, CURSO_ID, HORARIO_ID', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'centroRecaudacionDepositoses' => array(self::HAS_MANY, 'CentroRecaudacionDepositos', 'CURSO_EDICION_ID'),
            'certificados' => array(self::HAS_MANY, 'Certificado', 'CURSO_EDICION_ID'),
            'cURSO' => array(self::BELONGS_TO, 'Curso', 'CURSO_ID'),
            'hORARIO' => array(self::BELONGS_TO, 'Horario', 'HORARIO_ID'),
            'personas' => array(self::MANY_MANY, 'Persona', 'curso_edicion_has_personas(CURSO_EDICION_ID, PERSONA_ID)'),
            'evaluacionEstudiantes' => array(self::HAS_MANY, 'EvaluacionEstudiante', 'CURSO_EDICION_ID'),
            'faltasEstudiantes' => array(self::HAS_MANY, 'FaltasEstudiante', 'CURSO_EDICION_ID'),
            'formularios' => array(self::HAS_MANY, 'Formulario', 'CURSO_EDICION_ID'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'FECHA_INICIO' => Yii::t('app', 'Fecha Inicio'),
                'FECHA_FINALIZACION' => Yii::t('app', 'Fecha Finalizacion'),
                'AULA' => Yii::t('app', 'Aula'),
                'NRO_ESTUDIANTES' => Yii::t('app', 'Nro Estudiantes'),
                'CURSO_ID' => Yii::t('app', 'Curso'),
                'HORARIO_ID' => Yii::t('app', 'Horario'),
                'centroRecaudacionDepositoses' => null,
                'certificados' => null,
                'cURSO' => null,
                'hORARIO' => null,
                'personas' => null,
                'evaluacionEstudiantes' => null,
                'faltasEstudiantes' => null,
                'formularios' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('FECHA_INICIO', $this->FECHA_INICIO, true);
        $criteria->compare('FECHA_FINALIZACION', $this->FECHA_FINALIZACION, true);
        $criteria->compare('AULA', $this->AULA, true);
        $criteria->compare('NRO_ESTUDIANTES', $this->NRO_ESTUDIANTES);
        $criteria->compare('CURSO_ID', $this->CURSO_ID);
        $criteria->compare('HORARIO_ID', $this->HORARIO_ID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}