<?php

/**
 * This is the model base class for the table "persona".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Persona".
 *
 * Columns in table "persona" available as properties of the model,
 * followed by relations of table "persona" available as properties of the model.
 *
 * @property integer $ID
 * @property string $CEDULA
 * @property string $RUC
 * @property string $NOMBRES
 * @property string $APELLIDOS
 * @property string $DIRECCION
 * @property string $TELEFONO
 * @property string $TITULOS_ACADEMICOS
 * @property string $LUGAR_TRABAJO
 * @property string $TIPO_PERSONA
 * @property integer $NRO_CURSOS_APROBADOS
 *
 * @property Banco[] $bancos
 * @property CentroRecaudacionDepositos[] $centroRecaudacionDepositoses
 * @property Certificado[] $certificados
 * @property CursoEdicion[] $cursoEdicions
 * @property EvaluacionEstudiante[] $evaluacionEstudiantes
 * @property FaltasEstudiante[] $faltasEstudiantes
 * @property Formulario[] $formularios
 * @property Formulario[] $formularios1
 */
abstract class BasePersona extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'persona';
    }

    public static function representingColumn() {
        return 'CEDULA';
    }

    public function rules() {
        return array(
            array('ID, CEDULA, NOMBRES, APELLIDOS, DIRECCION, TELEFONO, LUGAR_TRABAJO, TIPO_PERSONA', 'required'),
            array('ID, NRO_CURSOS_APROBADOS', 'numerical', 'integerOnly'=>true),
            array('CEDULA, RUC, NOMBRES, APELLIDOS, TELEFONO, LUGAR_TRABAJO', 'length', 'max'=>20),
            array('DIRECCION', 'length', 'max'=>100),
            array('TITULOS_ACADEMICOS', 'length', 'max'=>70),
            array('TIPO_PERSONA', 'length', 'max'=>10),
            array('TIPO_PERSONA', 'in', 'range' => array('ESTUDIANTE','PARTICULAR','INSTRUCTOR')), // enum,
            array('RUC, TITULOS_ACADEMICOS, NRO_CURSOS_APROBADOS', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, CEDULA, RUC, NOMBRES, APELLIDOS, DIRECCION, TELEFONO, TITULOS_ACADEMICOS, LUGAR_TRABAJO, TIPO_PERSONA, NRO_CURSOS_APROBADOS', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'bancos' => array(self::HAS_MANY, 'Banco', 'PERSONA_ID'),
            'centroRecaudacionDepositoses' => array(self::HAS_MANY, 'CentroRecaudacionDepositos', 'PERSONA_ID'),
            'certificados' => array(self::HAS_MANY, 'Certificado', 'PERSONA_ID'),
            'cursoEdicions' => array(self::MANY_MANY, 'CursoEdicion', 'curso_edicion_has_personas(PERSONA_ID, CURSO_EDICION_ID)'),
            'evaluacionEstudiantes' => array(self::HAS_MANY, 'EvaluacionEstudiante', 'PERSONA_ID'),
            'faltasEstudiantes' => array(self::HAS_MANY, 'FaltasEstudiante', 'PERSONA_ID'),
            'formularios' => array(self::HAS_MANY, 'Formulario', 'ESTUDIANTE_ID'),
            'formularios1' => array(self::HAS_MANY, 'Formulario', 'INSTRUCTOR_ID'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'CEDULA' => Yii::t('app', 'Cedula'),
                'RUC' => Yii::t('app', 'Ruc'),
                'NOMBRES' => Yii::t('app', 'Nombres'),
                'APELLIDOS' => Yii::t('app', 'Apellidos'),
                'DIRECCION' => Yii::t('app', 'Direccion'),
                'TELEFONO' => Yii::t('app', 'Telefono'),
                'TITULOS_ACADEMICOS' => Yii::t('app', 'Titulos Academicos'),
                'LUGAR_TRABAJO' => Yii::t('app', 'Lugar Trabajo'),
                'TIPO_PERSONA' => Yii::t('app', 'Tipo Persona'),
                'NRO_CURSOS_APROBADOS' => Yii::t('app', 'Nro Cursos Aprobados'),
                'bancos' => null,
                'centroRecaudacionDepositoses' => null,
                'certificados' => null,
                'cursoEdicions' => null,
                'evaluacionEstudiantes' => null,
                'faltasEstudiantes' => null,
                'formularios' => null,
                'formularios1' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('CEDULA', $this->CEDULA, true);
        $criteria->compare('RUC', $this->RUC, true);
        $criteria->compare('NOMBRES', $this->NOMBRES, true);
        $criteria->compare('APELLIDOS', $this->APELLIDOS, true);
        $criteria->compare('DIRECCION', $this->DIRECCION, true);
        $criteria->compare('TELEFONO', $this->TELEFONO, true);
        $criteria->compare('TITULOS_ACADEMICOS', $this->TITULOS_ACADEMICOS, true);
        $criteria->compare('LUGAR_TRABAJO', $this->LUGAR_TRABAJO, true);
        $criteria->compare('TIPO_PERSONA', $this->TIPO_PERSONA, true);
        $criteria->compare('NRO_CURSOS_APROBADOS', $this->NRO_CURSOS_APROBADOS);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}