<?php

/**
 * This is the model base class for the table "persona_frg1".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonaFrg1".
 *
 * Columns in table "persona_frg1" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ID
 * @property string $FOTO
 *
 */
abstract class BasePersonaFrg1 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'persona_frg1';
    }

    public static function representingColumn() {
        return 'FOTO';
    }

    public function rules() {
        return array(
            array('ID', 'required'),
            array('ID', 'numerical', 'integerOnly'=>true),
            array('FOTO', 'safe'),
            array('FOTO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, FOTO', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'FOTO' => Yii::t('app', 'Foto'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('FOTO', $this->FOTO, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}