<?php

/**
 * This is the model base class for the table "banco_deposito".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BancoDeposito".
 *
 * Columns in table "banco_deposito" available as properties of the model,
 * followed by relations of table "banco_deposito" available as properties of the model.
 *
 * @property integer $ID
 * @property string $NRO_COMPROBANTE
 * @property string $VALOR
 * @property integer $BANCO_ID
 * @property integer $CURSO_EDICION_ID
 *
 * @property CursoEdicion $cURSOEDICION
 * @property Banco $bANCO
 */
abstract class BaseBancoDeposito extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'banco_deposito';
    }

    public static function representingColumn() {
        return 'NRO_COMPROBANTE';
    }

    public function rules() {
        return array(
            array('NRO_COMPROBANTE, VALOR, BANCO_ID, CURSO_EDICION_ID', 'required'),
            array('BANCO_ID, CURSO_EDICION_ID', 'numerical', 'integerOnly'=>true),
            array('NRO_COMPROBANTE', 'length', 'max'=>20),
            array('VALOR', 'length', 'max'=>10),
            array('ID, NRO_COMPROBANTE, VALOR, BANCO_ID, CURSO_EDICION_ID', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cURSOEDICION' => array(self::BELONGS_TO, 'CursoEdicion', 'CURSO_EDICION_ID'),
            'bANCO' => array(self::BELONGS_TO, 'Banco', 'BANCO_ID'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'NRO_COMPROBANTE' => Yii::t('app', 'Nro Comprobante'),
                'VALOR' => Yii::t('app', 'Valor'),
                'BANCO_ID' => Yii::t('app', 'Banco'),
                'CURSO_EDICION_ID' => Yii::t('app', 'Curso Edicion'),
                'cURSOEDICION' => null,
                'bANCO' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID);
        $criteria->compare('NRO_COMPROBANTE', $this->NRO_COMPROBANTE, true);
        $criteria->compare('VALOR', $this->VALOR, true);
        $criteria->compare('BANCO_ID', $this->BANCO_ID);
        $criteria->compare('CURSO_EDICION_ID', $this->CURSO_EDICION_ID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}